--join_study.sql

SELECT 
    S.NAME,
    S.SEQ,
    P.STAFF_SEQ,
    P.PROJECT
FROM TBLSTAFF S, TBLPROJECT P
    WHERE S.SEQ = P.STAFF_SEQ;
    
SELECT 
    S.NAME,
    S.SEQ,
    P.STAFF_SEQ,
    P.PROJECT
FROM TBLSTAFF S 
    FULL OUTER JOIN TBLPROJECT P 
        ON S.SEQ = P.STAFF_SEQ;
    
SELECT * FROM TBLSTAFF;
SELECT * FROM TBLPROJECT;

SELECT * FROM TBLSELF;

SELECT 
    S1.SEQ,
    S1.NAME, S1.SUPER,
    S2.SEQ,
    S2.NAME, S2.SUPER
FROM TBLSELF S1, TBLSELF S2
    WHERE S1.SUPER = S2.SEQ(+);
    


SELECT * FROM TBLCUSTOMER;
SELECT * FROM TBLSALES;

SELECT 
    C.NAME,
    S.ITEM,
    S.QTY,
    S.REGDATE
FROM TBLCUSTOMER C, TBLSALES S
    WHERE C.SEQ = S.CSEQ;
    

CREATE TABLE JIK (
    SEQ NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    SALARY NUMBER NOT NULL
);
CREATE TABLE PRO (
    SEQ NUMBER PRIMARY KEY,
    PROJECT VARCHAR2(300) NULL,
    JSEQ NUMBER NOT NULL REFERENCES JIK(SEQ)
);

INSERT INTO JIK (SEQ, NAME, SALARY) VALUES (1, '김부장', 500);
INSERT INTO JIK (SEQ, NAME, SALARY) VALUES (2, '김과장', 400);
INSERT INTO JIK (SEQ, NAME, SALARY) VALUES (3, '이과장', 350);
INSERT INTO JIK (SEQ, NAME, SALARY) VALUES (4, '송팀장', 300);
INSERT INTO JIK (SEQ, NAME, SALARY) VALUES (5, '고팀장', 300);
INSERT INTO JIK (SEQ, NAME, SALARY) VALUES (6, '김대리', 150);
INSERT INTO JIK (SEQ, NAME, SALARY) VALUES (7, '김신입', 150);

INSERT INTO PRO (SEQ, PROJECT, JSEQ) VALUES (1, '비트코인', 1);
INSERT INTO PRO (SEQ, PROJECT, JSEQ) VALUES (2, '비트코인', 4);
INSERT INTO PRO (SEQ, PROJECT, JSEQ) VALUES (3, '비트코인', 5);
INSERT INTO PRO (SEQ, PROJECT, JSEQ) VALUES (4, '비트코인', 6);
INSERT INTO PRO (SEQ, PROJECT, JSEQ) VALUES (5, '비트코인', 2);
INSERT INTO PRO (SEQ, PROJECT, JSEQ) VALUES (6, '비트코인', 2);

INSERT INTO JIK (SEQ, NAME, SALARY) VALUES (8, '최신입', 100);
INSERT INTO PRO (SEQ, PROJECT, JSEQ) VALUES (7, '김치코인', 8);
INSERT INTO PRO (SEQ, PROJECT, JSEQ) VALUES (8, '김치코인', 9);


SELECT * FROM JIK;
SELECT * FROM PRO;

SELECT 
    J.SEQ,
    J.NAME,
    P.PROJECT
FROM JIK J
    INNER JOIN PRO P 
        ON J.SEQ = P.JSEQ;
        
        
SELECT * FROM TBLCUSTOMER;
SELECT * FROM TBLSALES;

SELECT SEQ FROM TBLCUSTOMER
    INNER JOIN TBLSALES
        ON TBLCUSTOMER.SEQ = TBLSALES.CSEQ;
        
        
SELECT 
    (SELECT NAME FROM TBLCUSTOMER WHERE TBLCUSTOMER.SEQ = TBLSALES.CSEQ) AS NAME,
    (SELECT TEL FROM TBLCUSTOMER WHERE TBLCUSTOMER.SEQ = TBLSALES.CSEQ) AS TEL,
    TBLSALES.ITEM
FROM tblSales;

SELECT 
    C.NAME,
    S.ITEM,
    S.QTY
FROM TBLCUSTOMER C 
    INNER JOIN TBLSALES S
        ON C.SEQ = S.CSEQ;


SELECT 
    *
FROM JIK J
    INNER JOIN PRO P
        ON J.SEQ = P.JSEQ;
        
SELECT * FROM TBLMEN;
SELECT * FROM TBLWOMEN;

SELECT 
    M.NAME,
    W.NAME 
FROM TBLMEN M
    INNER JOIN TBLWOMEN W
        ON M.COUPLE = W.NAME;
        
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;
SELECT * FROM EMPLOYEES;

SELECT
    E.FIRST_NAME AS NAME,
    D.DEPARTMENT_NAME,
    L.CITY || L.STREET_ADDRESS
FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
            INNER JOIN LOCATIONS L
                ON D.LOCATION_ID = L.LOCATION_ID;


SELECT * FROM TBLGENRE;
SELECT * FROM TBLVIDEO;
SELECT * FROM TBLRENT;
SELECT * FROM TBLMEMBER;

SELECT 
    G.NAME AS 장르이름,
    G.PERIOD AS 대여기간,
    V.NAME AS 비디오이름,
    R.RENTDATE AS 대여날짜,
    M.NAME AS 빌린사람이름,
    R.RENTDATE + G.PERIOD AS 반납날짜
FROM TBLGENRE G
    INNER JOIN TBLVIDEO V
        ON G.SEQ = V.GENRE
            INNER JOIN TBLRENT R
                ON V.SEQ = R.VIDEO
                    INNER JOIN TBLMEMBER M
                        ON M.SEQ = R.MEMBER;